### ISSUE TITLE
Request for Squad Composition

### ISSUE THREAD

**Issue by Drevarr** [Freyavf/arcdps_top_stats_parser#1]
Would if be difficult to add gathering the squad composition per fight for output?

```squad_comp = {fight_number: {profession1: count1, profession2: count2, ...}}```

bad pseudo code example as I am still trying to hack my way into this feature:
```
def gather_squad_composition():
    for fight in fights:
        squad_comp[fight]={}
        for player in players:
            if player.profession not in squad_comp[fight]:
                squad_comp[fight][player.profession] = 1
            else:
                Squad_comp[fight][player.profession] = squad_comp[fight][player.profession]+1
    return squad_comp
```

**Comment by Freyavf** [comment]
That shouldn't be a problem :) Would it be ok if I add it in the fights list? So
fights = [ {"allies": 33, ..., "squad_comp": {prof1: count1, prof2: count2,...}, ... }, ... ]

Or would you prefer it in a separate list like you put it?

**Comment by Drevarr** [comment]
Either way would be great, anything you do will be much more elegant.

I am currently collecting squad_comp inside  ```def collect_stat_data(args, config, log, anonymize=False):```  and I am sure it is ugly but works.  Picking it back up in detailed.py @ ```players, fights, found_healing, found_barrier, squad_comp = collect_stat_data(args, config, log, args.anonymize)``` 

Love the current output of detailed.py, i just have it tacked on the end currently and need to clean it up to match the original.

**Comment by Drevarr** [comment]
Think I am settled on squad composition, probably need to make it a function and put it in tools.py to follow your structure.  Tonight's run will be the first parse with the new format.

Testing from in week log examples:
![image](https://user-images.githubusercontent.com/16168556/161632346-35d59ce9-7965-42cf-9cee-767ac2758ac5.png)


Again, thank you for this software I am really enjoying it.
