### ISSUE TITLE
Detailed runs ok, Overview fails on regen

### ISSUE THREAD

**Issue by Drevarr** [Freyavf/arcdps_top_stats_parser#2]
```py 
Traceback (most recent call last):
  File "D:\Freya_TOPSTATS\parse_top_stats_overview.py", line 75, in <module>
    overall_squad_stats = get_overall_squad_stats(fights, config)
  File "D:\Freya_TOPSTATS\parse_top_stats_tools.py", line 1008, in get_overall_squad_stats
    overall_squad_stats[stat] = overall_squad_stats[stat] * 100
KeyError: 'regen'

(base) D:\Freya_TOPSTATS>
```

[RegenTestLogs and jsonoutput.zip](https://github.com/Freyavf/arcdps_top_stats_parser/files/10582002/RegenTestLogs.and.jsonoutput.zip)

**Comment by Drevarr** [comment]
It has been so long since I ran overview, I forgot there were two config files for detailed and overview.

buffs are in `config.buff_ids` (l:1006) from buffMap but not in `config.stats_to_compute` (l:1001)

indentation maybe?

**Comment by Freyavf** [comment]
same, I haven't looked at overview in forever... I thought about scrapping it, but maybe it's good to keep it for testing purposes :D 
I changed your suggestion a bit so it still does it for all buffs :) If it looks good to you, I'll merge the pull request in.
