### ISSUE TITLE
Parser fails with Python 3.13

### ISSUE THREAD

**Issue by mvieths** [Freyavf/arcdps_top_stats_parser#35]
Python 3.13 removed the 'cgi' module, which is used in TW5_parse_top_stats_tools.py.

https://docs.python.org/3/library/cgi.html

**Comment by Freyavf** [comment]
You're probably looking at Drevarr's fork, since this version doesn't have a TW5_parse_top_stats_tools.py: https://github.com/Drevarr/arcdps_top_stats_parser
Please open an issue there :)

**Comment by mvieths** [comment]
Woops, my mistake.  Thank you.
